// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    GoodbyeWorld: typeof import('./src/components/GoodbyeWorld.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Hexgrid: typeof import('./src/pages/PSO/hexgrid.vue')['default']
    Hexgrid2: typeof import('./src/pages/PSO/hexgrid2.vue')['default']
    Middle: typeof import('./src/pages/Middle/index.vue')['default']
    PSO: typeof import('./src/pages/PSO/index.vue')['default']
    Router: typeof import('./src/pages/router.ts')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sigil: typeof import('./src/pages/PSO/sigil.vue')['default']
    Start: typeof import('./src/pages/Start/index.vue')['default']
  }
}
