// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BgText: typeof import('./src/pages/PSO/bgText.vue')['default']
    BgTextF: typeof import('./src/pages/JSFree/bgTextF.vue')['default']
    GoodbyeWorld: typeof import('./src/components/GoodbyeWorld.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Hexgrid: typeof import('./src/components/hexgrid.vue')['default']
    Hexgrid2: typeof import('./src/components/hexgrid2.vue')['default']
    JSFree: typeof import('./src/pages/JSFree/index.vue')['default']
    Middle: typeof import('./src/pages/Middle/index.vue')['default']
    Orbs: typeof import('./src/components/orbs.vue')['default']
    PSO: typeof import('./src/pages/PSO/index.vue')['default']
    Router: typeof import('./src/pages/router.ts')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sigil: typeof import('./src/components/sigil.vue')['default']
    Starburst: typeof import('./src/pages/JSFree/starburst.vue')['default']
    StarStream: typeof import('./src/pages/PSO/starStream.vue')['default']
    StarStreamF: typeof import('./src/pages/JSFree/starStreamF.vue')['default']
    Start: typeof import('./src/pages/Start/index.vue')['default']
    Title: typeof import('./src/components/title.vue')['default']
    Twinkle: typeof import('./src/pages/PSO/twinkle.vue')['default']
    UseTwo: typeof import('./src/pages/PSO/useTwo.ts')['default']
  }
}
